// <auto-generated />
using Crypts_And_Coders.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crypts_And_Coders.Migrations
{
    [DbContext(typeof(CryptsDbContext))]
    [Migration("20200803203123_addedWeaponsDbSet")]
    partial class addedWeaponsDbSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crypts_And_Coders.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Character");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = 3,
                            LocationId = 1,
                            Name = "Galdifor",
                            Species = 1,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 2,
                            Class = 0,
                            LocationId = 1,
                            Name = "Dragorn",
                            Species = 3,
                            WeaponId = 1
                        },
                        new
                        {
                            Id = 3,
                            Class = 4,
                            LocationId = 1,
                            Name = "Glen",
                            Species = 0,
                            WeaponId = 1
                        });
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.CharacterInventory", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterInventory");
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Species")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enemy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abilities = "Slash",
                            Species = 6,
                            Type = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Abilities = "Smash",
                            Species = 7,
                            Type = "Beast"
                        },
                        new
                        {
                            Id = 3,
                            Abilities = "Firebreath",
                            Species = 8,
                            Type = "Mythical"
                        });
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Health Potion",
                            Value = 25
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cup",
                            Value = 5
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dungeon Key",
                            Value = 100
                        });
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Occupied by the forces of evil, Faldor consists of open, hilly plains that separate it's eastern border with towering mountains.",
                            Name = "Faldor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Plagued by the great war, Murkden remains uninhibited from all intelligent life forms, although various beasts still dwell in the deep marshes.",
                            Name = "Murkden"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lyderton is full of simpletons who prefer to keep war and conflict outside of their borders. It is rich farmland with dense amounts of beautiful wildlife.",
                            Name = "Lyderton"
                        });
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseDamage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseDamage = 15,
                            Name = "Claymore",
                            Type = "Close Range"
                        },
                        new
                        {
                            Id = 2,
                            BaseDamage = 18,
                            Name = "Wizard Staff",
                            Type = "Magical"
                        },
                        new
                        {
                            Id = 3,
                            BaseDamage = 10,
                            Name = "Longbow",
                            Type = "Long Range"
                        });
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.Character", b =>
                {
                    b.HasOne("Crypts_And_Coders.Models.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crypts_And_Coders.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Crypts_And_Coders.Models.CharacterInventory", b =>
                {
                    b.HasOne("Crypts_And_Coders.Models.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crypts_And_Coders.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
